version: "3.9"

services:
  proxy:
    build: ./proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/ssl/certs/nginx/:ro
    networks:
      - dev
    environment:
      - REVERSE_PROXY_SCHEME=https
      - SERVER_PORT=3000
      - CLIENT_PORT=3030
      - USE_CERTBOT=false
  
  client:
    build: ./dev
    networks:
      - dev
    volumes:
      - ./ssl:/etc/ssl/certs/nginx/:ro
    environment:
      - LOCAL_PORT=3030
      - REMOTE_PORT=3030
  
  server:
    build: ./dev
    depends_on:
      - "db"
    networks:
      - dev
    volumes:
      - ./ssl:/etc/ssl/certs/nginx/:ro
    environment:
      - LOCAL_PORT=3000
      - REMOTE_PORT=3000

  db:
    image: postgres
    restart: always
    networks:
      - dev
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=smt

networks:
  dev:
